name: Publish to npm

on:
  release:
    types: [created]

jobs:
  test:
    name: Run tests before publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Run tests
        run: npm test
        env:
          NVENV_SILENT: 1

      - name: Test package creation
        run: |
          node src/cli.js --node=18.20.0 test-publish-env
          test -d test-publish-env/bin
          test -d test-publish-env/lib

  publish:
    name: Publish to npm
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write  # Required for provenance

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Verify package contents
        run: |
          npm pack --dry-run
          echo "Package contents verified"

      - name: Publish to npm with provenance
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Extract version from package.json
        id: version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Get release tag
        id: tag
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Comment on release
        uses: actions/github-script@v7
        with:
          script: |
            const version = '${{ steps.version.outputs.version }}';
            const tag = '${{ steps.tag.outputs.tag }}';

            github.rest.repos.createReleaseComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: context.payload.release.id,
              body: `✅ Successfully published to npm: https://www.npmjs.com/package/nvenv/v/${version}`
            });
